version: "3.0"

services:
  db:
    image: hotel_ventura_db
    build: ./mysql
    container_name: hotel_ventura_db
    ports:
      - 3306:3306
  cache:
    build: ./redis
    container_name: hotel_ventura_redis
    ports:
      - 6379:6379
